/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkingGroupsRouteImport } from './routes/working-groups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'

const WorkingGroupsRoute = WorkingGroupsRouteImport.update({
  id: '/working-groups',
  path: '/working-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/working-groups': typeof WorkingGroupsRoute
  '/apps/$appId': typeof AppsAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/working-groups': typeof WorkingGroupsRoute
  '/apps/$appId': typeof AppsAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/working-groups': typeof WorkingGroupsRoute
  '/apps/$appId': typeof AppsAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/working-groups' | '/apps/$appId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/working-groups' | '/apps/$appId'
  id: '__root__' | '/' | '/working-groups' | '/apps/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkingGroupsRoute: typeof WorkingGroupsRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/working-groups': {
      id: '/working-groups'
      path: '/working-groups'
      fullPath: '/working-groups'
      preLoaderRoute: typeof WorkingGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkingGroupsRoute: WorkingGroupsRoute,
  AppsAppIdRoute: AppsAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
