/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkingGroupsRouteImport } from './routes/working-groups'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'

const WorkingGroupsRoute = WorkingGroupsRouteImport.update({
  id: '/working-groups',
  path: '/working-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRoute
  '/organization': typeof OrganizationRoute
  '/training': typeof TrainingRoute
  '/working-groups': typeof WorkingGroupsRoute
  '/apps/$appId': typeof AppsAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRoute
  '/organization': typeof OrganizationRoute
  '/training': typeof TrainingRoute
  '/working-groups': typeof WorkingGroupsRoute
  '/apps/$appId': typeof AppsAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRoute
  '/organization': typeof OrganizationRoute
  '/training': typeof TrainingRoute
  '/working-groups': typeof WorkingGroupsRoute
  '/apps/$appId': typeof AppsAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/communication'
    | '/organization'
    | '/training'
    | '/working-groups'
    | '/apps/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/communication'
    | '/organization'
    | '/training'
    | '/working-groups'
    | '/apps/$appId'
  id:
    | '__root__'
    | '/'
    | '/communication'
    | '/organization'
    | '/training'
    | '/working-groups'
    | '/apps/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunicationRoute: typeof CommunicationRoute
  OrganizationRoute: typeof OrganizationRoute
  TrainingRoute: typeof TrainingRoute
  WorkingGroupsRoute: typeof WorkingGroupsRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/working-groups': {
      id: '/working-groups'
      path: '/working-groups'
      fullPath: '/working-groups'
      preLoaderRoute: typeof WorkingGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunicationRoute: CommunicationRoute,
  OrganizationRoute: OrganizationRoute,
  TrainingRoute: TrainingRoute,
  WorkingGroupsRoute: WorkingGroupsRoute,
  AppsAppIdRoute: AppsAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
